import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {apiRequest,getConnection,setConnection,startMiniServer} from './server';

const USERS=[{id:'Manager',password:'manager001',role:'manager',name:'Manager'},{id:'Manager-001',password:'manager001',role:'manager',name:'Manager 001'},{id:'staff001',password:'staff001',role:'staff',name:'Staff 001'},{id:'staff002',password:'staff002',role:'staff',name:'Staff 002'}];
const SECTIONS=['Biryani Section','Fried Section'];
const DEFAULT_MENU=[{id:'bir-full',name:'Chicken Biryani Full',category:'Biryani',section:SECTIONS[0],price:180,image:''},{id:'bir-family',name:'Biryani Family Pack',category:'Biryani',section:SECTIONS[0],price:650,image:''},{id:'mutton-bir',name:'Mutton Biryani',category:'Biryani',section:SECTIONS[0],price:260,image:''},{id:'ch65',name:'Chicken 65',category:'Fried',section:SECTIONS[1],price:180,image:''},{id:'ch-tandoori',name:'Chicken Tandoori',category:'Fried',section:SECTIONS[1],price:240,image:''}];
const DEFAULT_STAFF=[{id:'staff001',name:'Staff 001',position:'Biryani Staff',section:SECTIONS[0]},{id:'staff002',name:'Staff 002',position:'Fried Staff',section:SECTIONS[1]}];
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const money=v=>`₹${Number(v||0).toFixed(2)}`;
function speak(t){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}
const readImage=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});
async function LoginServer(){try{return await startMiniServer(getConnection()?.key||'')}catch{return null}}

function Login({onLogin}){const[id,setId]=useState('Manager'),[pw,setPw]=useState('manager001'),[url,setUrl]=useState(getConnection()?.url||''),[key,setKey]=useState(getConnection()?.key||''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const manager=/^manager/i.test(id.trim());async function submit(e){e.preventDefault();setErr('');setBusy(true);try{const u=USERS.find(x=>x.id.toLowerCase()===id.trim().toLowerCase()&&x.password===pw);if(!u)throw Error('Invalid User ID or password');if(u.role==='manager'){if(!await LoginServer())throw Error('Manager Mini Server could not start. Install the Android APK for two-device testing.')}else{if(!url.trim()||!key.trim())throw Error('Enter Manager server URL and Hotel Key first.');setConnection({url:url.trim().replace(/\/$/,''),key:key.trim()});await apiRequest('/api/state')}save('koms_session',u);onLogin(u)}catch(e){setErr(e.message)}finally{setBusy(false)}}return <div className="login-page"><div className="login-card"><div className="brand-mark">🍽️</div><h1>Hotel Order Manager</h1><p>Local Mini-Server Kitchen System</p><form onSubmit={submit}><label>User ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>Password<input type="password" value={pw} onChange={e=>setPw(e.target.value)}/></label>{!manager&&<><label>Manager Server URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="http://192.168.43.1:8787"/></label><label>Hotel Connection Key<input value={key} onChange={e=>setKey(e.target.value)} placeholder="HOTEL-XXXXXXXX"/></label></>}{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy}>{busy?'Connecting…':'Login'}</button></form><div className="demo-box"><b>Manager</b> Manager / manager001<br/><b>Kitchen</b> staff001 / staff001 · staff002 / staff002</div></div></div>}

function App(){const[user,setUser]=useState(()=>load('koms_session',null));const deliveryMode=useMemo(()=>new URLSearchParams(location.search).get('delivery')==='1',[]);const[view,setView]=useState(()=>deliveryMode?'delivery':load('koms_view','counter'));const[menu,setMenu]=useState(()=>load('koms_menu',DEFAULT_MENU)),[staff,setStaff]=useState(()=>load('koms_staff',DEFAULT_STAFF)),[orders,setOrders]=useState(()=>load('koms_orders',[])),[cart,setCart]=useState([]),[category,setCategory]=useState('All'),[lastSync,setLastSync]=useState(new Date()),[serverInfo,setServerInfo]=useState(getConnection()),[error,setError]=useState('');const known=useRef(new Set(load('koms_orders',[]).map(x=>x.id)));useEffect(()=>save('koms_view',view),[view]);
 const refresh=async({announce=true}={})=>{try{const s=await apiRequest('/api/state');const os=s.orders||[],ms=s.menu?.length?s.menu:DEFAULT_MENU,ss=s.staff?.length?s.staff:DEFAULT_STAFF;const fresh=os.filter(o=>!known.current.has(o.id));setOrders(os);setMenu(ms);setStaff(ss);setLastSync(new Date());setServerInfo(getConnection());setError('');fresh.forEach(o=>known.current.add(o.id));if(announce&&user?.role==='staff'){const sec=ss.find(x=>x.id===user.id)?.section;fresh.forEach(o=>{const ts=(o.tasks||[]).filter(t=>t.section===sec&&t.status==='New');if(ts.length)speak(`New order. Token ${o.token}. ${ts.flatMap(t=>t.items.map(i=>`${i.qty} ${i.name}`)).join(', ')}`)})}save('koms_orders',os);save('koms_menu',ms);save('koms_staff',ss);if(user?.role==='manager'&&(!s.menu?.length||!s.staff?.length)){if(!s.menu?.length)await apiRequest('/api/menu',{method:'POST',body:JSON.stringify(DEFAULT_MENU)});if(!s.staff?.length)await apiRequest('/api/staff',{method:'POST',body:JSON.stringify(DEFAULT_STAFF)}}catch(e){setError(e.message||'Manager server unavailable')}};
 useEffect(()=>{if(!user)return;refresh({announce:false});const t=setInterval(()=>refresh({announce:true}),15000);return()=>clearInterval(t)},[user]);
 if(!user)return <Login onLogin={u=>{setUser(u);setView(u.role==='manager'?'counter':'kitchen')}}/>;
 const cats=['All',...new Set(menu.map(x=>x.category).filter(Boolean))],visible=category==='All'?menu:menu.filter(x=>x.category===category),mySection=staff.find(x=>x.id===user.id)?.section,kitchen=orders.filter(o=>(o.tasks||[]).some(t=>t.section===mySection&&t.status!=='Completed')&&o.status!=='Collected'),ready=orders.filter(o=>o.status==='Ready'),total=cart.reduce((s,x)=>s+Number(x.price||0)*x.qty,0);
 const add=i=>setCart(c=>{const old=c.find(x=>x.id===i.id);return old?c.map(x=>x.id===i.id?{...x,qty:x.qty+1}:x):[...c,{...i,qty:1,note:''}]}),change=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+d}:x).filter(x=>x.qty>0)),note=(id,n)=>setCart(c=>c.map(x=>x.id===id?{...x,note:n}:x));
 async function createOrder(){if(!cart.length)return;try{const tasks=cart.reduce((a,i)=>{const t=a.find(x=>x.section===i.section),item={name:i.name,qty:i.qty,unitPrice:Number(i.price||0),total:Number(i.price||0)*i.qty,note:(i.note||'').trim()};if(t)t.items.push(item);else a.push({section:i.section,items:[item],status:'New'});return a},[]);const o=await apiRequest('/api/order',{method:'POST',body:JSON.stringify({createdBy:user.id,tasks,total,itemCount:cart.reduce((n,x)=>n+x.qty,0)})});const s=await apiRequest('/api/state');setOrders(s.orders||[]);known.current.add(o.id);speak(`New order. Token number ${o.token}. Total ${money(total)}.`);setCart([])}catch(e){setError(e.message)}}
 async function task(orderId,section,status){try{await apiRequest('/api/task',{method:'POST',body:JSON.stringify({orderId,section,status})});await refresh({announce:false})}catch(e){setError(e.message)}}async function collect(id){try{await apiRequest('/api/collect',{method:'POST',body:JSON.stringify({orderId:id})});await refresh({announce:false})}catch(e){setError(e.message)}}async function saveMenu(next){setMenu(next);save('koms_menu',next);try{await apiRequest('/api/menu',{method:'POST',body:JSON.stringify(next)})}catch(e){setError(e.message)}}async function saveStaff(next){setStaff(next);save('koms_staff',next);try{await apiRequest('/api/staff',{method:'POST',body:JSON.stringify(next)})}catch(e){setError(e.message)}}
 return <div className="app"><header><div><b>🍽️ Hotel Order Manager</b><span className="user-pill">{user.name} · {user.role}</span></div><div className="sync-indicator">{serverInfo?.url||'Mini Server'} · {lastSync.toLocaleTimeString()}</div><button className="logout" onClick={()=>{setUser(null);localStorage.removeItem('koms_session')}}>Logout</button></header><nav>{user.role==='manager'&&!deliveryMode&&<><button className={view==='counter'?'active':''} onClick={()=>setView('counter')}>Counter</button><button className={view==='menu'?'active':''} onClick={()=>setView('menu')}>Menu</button><button className={view==='manage'?'active':''} onClick={()=>setView('manage')}>Staff & Sections</button><button className={view==='delivery'?'active':''} onClick={()=>setView('delivery')}>Delivery</button></>}{!deliveryMode&&<button className={view==='kitchen'?'active':''} onClick={()=>setView('kitchen')}>{user.role==='staff'?mySection:'Kitchen'}</button>}{deliveryMode&&<button className="active">Delivery Counter</button>}</nav>{error&&<div className="error" style={{margin:'12px auto',maxWidth:1000}}>{error}</div>}{view==='counter'&&user.role==='manager'&&<Counter cats={cats} category={category} setCategory={setCategory} menu={visible} cart={cart} add={add} change={change} note={note} total={total} createOrder={createOrder}/>} {view==='menu'&&user.role==='manager'&&<MenuManager menu={menu} onSave={saveMenu}/>} {view==='kitchen'&&<Kitchen user={user} orders={user.role==='staff'?kitchen:orders} onTask={task}/>} {view==='manage'&&user.role==='manager'&&<Manage staff={staff} onSave={saveStaff}/>} {view==='delivery'&&<Delivery orders={ready} onCollect={collect}/>}</div>}

function Counter({cats,category,setCategory,menu,cart,add,change,note,total,createOrder}){return <main className="grid"><section className="panel"><h2>New Order</h2><div className="chips">{cats.map(c=><button className={category===c?'chip active':'chip'} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="menu-grid">{menu.map(i=><button className="menu-item" onClick={()=>add(i)} key={i.id}>{i.image?<img className="menu-image" src={i.image} alt=""/>:<div className="menu-image placeholder-food">🍽️</div>}<div className="menu-info"><b>{i.name}</b><small>{i.section}</small><strong>{money(i.price)}</strong></div></button>)}</div></section><section className="panel cart"><h2>Current Order</h2>{!cart.length?<div className="empty">No items selected</div>:cart.map(i=><div className="cart-row" key={i.id}><div className="cart-item-info">{i.image&&<img className="cart-thumb" src={i.image} alt=""/>}<div><b>{i.name}</b><small>{money(i.price)} × {i.qty}</small></div><textarea className="item-note" value={i.note||''} onChange={e=>note(i.id,e.target.value)} maxLength={160} placeholder="Kitchen note" rows={2}/></div><div className="qty"><button onClick={()=>change(i.id,-1)}>−</button><b>{i.qty}</b><button onClick={()=>change(i.id,1)}>+</button></div><strong className="line-total">{money(Number(i.price||0)*i.qty)}</strong></div>)}<div className="cart-total"><span>Grand Total</span><b>{money(total)}</b></div><button className="primary full" disabled={!cart.length} onClick={createOrder}>Create Order · {money(total)} · Generate Token</button></section></main>}

function MenuManager({menu,onSave}){const empty={id:'',name:'',category:'Biryani',section:SECTIONS[0],price:'',image:''};const[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false);const reset=()=>{setForm(empty);setEditing(null)};const edit=i=>{setEditing(i.id);setForm({...i,price:String(i.price??'')})};async function choose(e){const f=e.target.files?.[0];if(!f)return;if(f.size>1200000){alert('Please choose an image under 1.2 MB.');return}try{const image=await readImage(f);setForm(x=>({...x,image}))}catch{alert('Could not read image.')}}async function submit(e){e.preventDefault();if(!form.name.trim())return;setBusy(true);const item={...form,id:editing||crypto.randomUUID(),name:form.name.trim(),category:form.category.trim()||'Other',section:form.section,price:Math.max(0,Number(form.price)||0),image:form.image||''};await onSave(editing?menu.map(x=>x.id===editing?item:x):[...menu,item]);setBusy(false);reset()}return <main className="panel wide"><div className="title-row"><div><h2>Menu Management</h2><p>Upload food image, set price, category and kitchen section.</p></div><button className="primary" onClick={reset}>+ New Item</button></div><form className="menu-form" onSubmit={submit}><div className="image-upload"><div className="upload-preview">{form.image?<img src={form.image} alt="Preview"/>:<span>🍽️</span>}</div><label className="upload-button">{form.image?'Change Food Image':'Upload Food Image'}<input type="file" accept="image/*" onChange={choose}/></label><small>JPG/PNG/WebP · max 1.2 MB</small></div><div className="form-fields"><label>Food Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Price (₹)<input required type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Kitchen Section<select value={form.section} onChange={e=>setForm({...form,section:e.target.value})}>{SECTIONS.map(s=><option key={s}>{s}</option>)}</select></label><div className="form-actions"><button className="primary" disabled={busy}>{editing?'Update Item':'Add Item'}</button>{editing&&<button type="button" onClick={reset}>Cancel</button>}</div></div></form><h3 className="menu-list-title">Current Menu · {menu.length} items</h3><div className="manage-menu-grid">{menu.map(i=><MenuCard key={i.id} item={i} onEdit={edit} onDelete={()=>onSave(menu.filter(x=>x.id!==i.id))}/>)}</div></main>}
function MenuCard({item,onEdit,onDelete}){return <div className="manage-menu-card">{item.image?<img src={item.image} alt=""/>:<div className="manage-placeholder">🍽️</div>}<div className="manage-menu-body"><b>{item.name}</b><span>{item.category} · {item.section}</span><strong>{money(item.price)}</strong><div className="card-actions"><button onClick={()=>onEdit(item)}>Edit</button><button className="danger" onClick={()=>{if(confirm('Delete this menu item?'))onDelete()}}>Delete</button></div></div></div>}

function Kitchen({user,orders,onTask}){return <main className="panel wide"><h2>Kitchen Orders</h2><p>{user.role==='staff'?'Only your assigned section is shown.':'All kitchen sections'} · New-order check every 15 seconds.</p>{!orders.length?<div className="empty large">No active kitchen orders</div>:orders.slice().reverse().map(o=><div className="order-card" key={o.id}><div className="token">TOKEN #{String(o.token).padStart(3,'0')}</div>{o.tasks.map(t=><div className="task" key={t.section}><div><h3>{t.section}</h3>{t.items.map((i,n)=><div className="kitchen-item" key={n}>{i.name} × <b>{i.qty}</b>{i.note&&<div className="kitchen-note"><b>Note:</b> {i.note}</div>}</div>)}<span className={`status ${t.status.toLowerCase()}`}>{t.status}</span></div><div className="actions">{t.status==='New'&&<button className="primary" onClick={()=>onTask(o.id,t.section,'Accepted')}>Accept</button>}{t.status==='Accepted'&&<button className="primary" onClick={()=>onTask(o.id,t.section,'Processing')}>Processing</button>}{t.status==='Processing'&&<button className="success" onClick={()=>onTask(o.id,t.section,'Completed')}>Complete</button>}</div></div>)}{o.total!=null&&<div className="order-total">Order Total: <b>{money(o.total)}</b></div>}</div>)}</main>}
function Delivery({orders,onCollect}){return <main className="panel wide"><div className="title-row"><div><h2>Delivery Counter</h2><p>Orders appear here after all kitchen sections complete.</p></div><b>{orders.length} READY</b></div>{!orders.length?<div className="empty large">No orders ready for collection</div>:orders.slice().reverse().map(o=><div className="order-card" key={o.id}><div className="token">TOKEN #{String(o.token).padStart(3,'0')} <span className="status completed">READY FOR COLLECTION</span></div>{o.tasks.map(t=><div className="task" key={t.section}><div><h3>{t.section}</h3>{t.items.map((i,n)=><div className="kitchen-item" key={n}>{i.name} × <b>{i.qty}</b>{i.note&&<div className="kitchen-note"><b>Note:</b> {i.note}</div>}</div>)}</div></div>)}{o.total!=null&&<div className="order-total">Total: <b>{money(o.total)}</b></div>}<button className="success full" onClick={()=>onCollect(o.id)}>Customer Collected</button></div>)}</main>}
function Manage({staff,onSave}){const[sel,setSel]=useState(staff[0]?.id||'');const current=staff.find(x=>x.id===sel);return <main className="panel wide"><h2>Staff & Sections</h2><p>Manager assigns staff to kitchen sections.</p><div className="staff-list">{staff.map(s=><button className={s.id===sel?'staff-card selected':'staff-card'} onClick={()=>setSel(s.id)} key={s.id}><b>{s.id}</b><span>{s.name}</span><small>{s.position}</small><em>{s.section}</em></button>)}</div>{current&&<div className="assign"><h3>Assign {current.id}</h3>{SECTIONS.map(s=><button className={current.section===s?'primary':''} onClick={()=>onSave(staff.map(x=>x.id===current.id?{...x,section:s}:x))} key={s}>{s}</button>)}</div>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
